feature (SELC-1498): migrate to auth0
Akkroo/akkroo-sdk-php pull request #9
Opened 2020-11-26 10:46 UTC by dluschitsky

This PR addresses issue https://integrate.atlassian.net/browse/SELC-1498

2020-11-26 15:06 UTC, quetzyg approved these changes
Left a minor note, not blocking

2020-12-03 11:50 UTC, sablake requested changes

2020-12-03 11:50 UTC, sablake commented on src/Client.php
> +        'auth_endpoint' => 'https://integrate-unified-dev.auth0.com/oauth/token',
This needs to be the production domain. Ideally https://auth.integrate.com/. If it's not ready by the 9th, then use https://integrate-inc.auth0.com/ instead

Wait for @sriramgopaldevops & @quetzyg to confirm.

2020-12-14 13:13 UTC, dluschitsky commented
@quetzyg @sablake the Auth domain was changed to https://auth.integrate.com/.

2020-12-14 19:31 UTC, quetzyg commented
Looks good

2020-12-15 14:35 UTC, sablake approved these changes

2020-12-19 09:27 UTC, merged